name: capstone_project
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '3.2.3'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  camera: ^0.10.5+5
  charts_flutter: ^0.12.0
  cloud_firestore: ^4.12.2
  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.6.3
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  # flutter_local_notifications: ^16.1.0
  flutter_spinkit: ^5.2.0
  flutter_typeahead: ^5.0.1
  geocoding: ^2.0.0
  geolocator: ^10.1.0
  get: ^4.6.6
  google_nav_bar: ^5.0.6
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  # http: ^1.1.0
  http: ^0.13.6
  image: ^4.0.15
  # image_picker: ^1.0.4
  image_picker: ^1.0.5
  intl: ^0.17.0
  marquee: ^2.0.0
  path_provider: ^2.0.14
  permission_handler: ^11.0.1
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.8
  tflite: ^1.1.2
  translator: ^0.1.7
  webview_flutter: ^3.0.0
  google_translator: ^1.0.0
  youtube_player_flutter: ^8.1.2
  # tflite_flutter: ^0.10.4
  pedantic: ^1.9.2
  # flutter_pytorch: ^1.0.1
  fl_chart: ^0.45.0
  syncfusion_flutter_charts: ^19.3.47
  flutter_speed_dial: ^4.0.2
  pytorch_lite: ^4.2.4
  pigeon: ^11.0.0
  
  

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: ^0.9.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/newimage/agrosense.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/images
    # - assets/new_rice_pest/model_unquant.tflite
    # - assets/new_rice_pest/labels.txt
    # - assets/new_rice_disease/model_unquant.tflite
    # - assets/new_rice_disease/labels.txt
    - assets/images/rice.jpg
    - assets/images/coconut.jpg
    - assets/images/banana.jpg
    - assets/images/corn.jpg
    - assets/images/sugarcane.jpg
    - assets/images/mango.jpg
    - assets/images/pineapple.jpg
    - assets/images/cassava.jpeg
    - assets/images/coffee.jpg
    - assets/images/tomato.jpg
    - assets/images/google.jpg
    - assets/images/apple.jpg
    # - assets/rice_pest/model_unquant.tflite
    # - assets/rice_disease/model_unquant.tflite
    # - assets/rice_pest/labels.txt
    # - assets/rice_disease/labels.txt
    - assets/images/rice_disease.jpg
    - assets/images/rice_pest.jpg
    - assets/images/cloud-in-blue-sky.jpg
    - assets/images/icon-01.jpg
    - assets/images/clear.jpg
    - assets/images/cloudy.jpg
    - assets/images/rainy.jpg
    - assets/images/drizzle.png
    - assets/images/thunderstorm.png
    - assets/images/snow.jpg
    - assets/images/mist.png
    - assets/images/farm.png
    - assets/images/newimage/
    # - assets/detect_pest/detect.tflite
    # - assets/detect_pest/labels.txt
    # - assets/detect_pest/new.tflite
    # - assets/detect_pest/ricepestyolo.tflite
    # - assets/detect_pest/labelmap.txt
    - assets/models/
    - assets/labels/
    - assets/images/
    - assets/images/dentskanload.gif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: flutterfont
      fonts:
        - asset: assets/fonts/flutterfonts.ttf
    # - family: OpenSans
    #   fonts:
    #     - asset: fonts/Open_Sans/OpenSans-Italic-VariableFont_wdth,wght.ttf
    #     - asset: fonts/Open_Sans/OpenSans-VariableFont_wdth,wght.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
