// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIVTpWGr6cZw9Rux_f4x7PIoDSfDgFzzE',
    appId: '1:240800815641:web:22cf5ea02f7adff944a888',
    messagingSenderId: '240800815641',
    projectId: 'capstone-project-71a6a',
    authDomain: 'capstone-project-71a6a.firebaseapp.com',
    storageBucket: 'capstone-project-71a6a.appspot.com',
    measurementId: 'G-4MSSQCBFSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8YpFPYu1qApb1x9gMYVEZZB1f63yRSXM',
    appId: '1:240800815641:android:6b96cb21381cae1944a888',
    messagingSenderId: '240800815641',
    projectId: 'capstone-project-71a6a',
    storageBucket: 'capstone-project-71a6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAky_rxNJe95yukQU2PEqSt9EwWlGhnDdo',
    appId: '1:240800815641:ios:1227c2d39aabdf3a44a888',
    messagingSenderId: '240800815641',
    projectId: 'capstone-project-71a6a',
    storageBucket: 'capstone-project-71a6a.appspot.com',
    iosClientId: '240800815641-q25vsob8vn95i5oih004dajlirlruikj.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAky_rxNJe95yukQU2PEqSt9EwWlGhnDdo',
    appId: '1:240800815641:ios:656745295b77cff044a888',
    messagingSenderId: '240800815641',
    projectId: 'capstone-project-71a6a',
    storageBucket: 'capstone-project-71a6a.appspot.com',
    iosClientId: '240800815641-v8nae1k0q9u2nmjl6mgvvh1sc7qf4aeg.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneProject.RunnerTests',
  );
}
